-- GENERAL_TRADE added to InvoiceType and VoucherType enums (Prisma client / TEXT columns).
-- No table or column changes required; historical PURCHASE_GENERAL and SALE_GENERAL rows stay valid.
-- Intentionally empty: SQLite stores these enums as TEXT, so no DDL is needed.
